main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls'))
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

from . import views


app_name = 'users'
urlpatterns = [
    path('', views.users_list, name='users_list'),
    path('profile/', views.profile, name='profile'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile_images/models.py
from django.db import models
from pathlib import Path

def get_upload_path(instance, filename):
    ''' Calculate and return an upload path for a profile image
        which includes the user's username '''
    # get the file's extension 
    file_extension = filename.split('.')[-1].lower()

    if file_extension == 'jpeg':
        file_extension = 'jpg'

    file_path = f'profile_images/default_profile_image.{file_extension}'

    if instance.has_custom_user():
        # upload to profile_images/<USERNAME>/
        file_path = Path(f'profile_images/{instance.customuser.username}/profile_image.{file_extension}') 
    
    # file path must be a string
    return str(file_path)

class ProfileImage(models.Model):
    image = models.ImageField(
        verbose_name='profile image',
        default='profile_images/default_profile_image.jpg',
        upload_to=get_upload_path,
    )

    def has_custom_user(self):
        return self.customuser is not None

    def __str__(self):
        return f'{self}'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from profile_images.models import ProfileImage

class CustomUser(AbstractUser):
    profile_image = models.OneToOneField(
        ProfileImage,
        null=True,
        on_delete = models.SET_NULL
    )

    def has_profile_image(self):
        return self.profile_image is not None

    def __str__(self):
        return self.username

profile_images/forms.py
from django import forms

from .models import ProfileImage

class ProfileImageUpdateForm(forms.ModelForm):
    class Meta:
        model = ProfileImage
        fields = ['image']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser

# extend UserCreationForm
class UserSignupForm(UserCreationForm):
    class Meta:
        # the model on which to base the form
        model = CustomUser

        # these fields will show up when the form is rendered
        fields = ['username', 'password1', 'password2']

profile_images/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render, redirect, reverse
from django.conf import settings

from .models import CustomUser
from .forms import UserSignupForm

from profile_images.models import ProfileImage
from profile_images.forms import ProfileImageUpdateForm

from pathlib import Path, PurePath
from PIL import Image

def signup(request):
    # blank instance of UserCreationForm
    form = UserSignupForm()
    
    if request.method == 'POST':

        # create a form with the form data from the request
        form = UserSignupForm(request.POST)    

        # validate the form
        if form.is_valid():

            # create a model object but don't save it yet
            new_user = form.save(commit=False)

            # create a new profile image object
            profile_image = ProfileImage.objects.create()

            # associate the profile image to the new user
            new_user.profile_image = profile_image

            # save new CustomUser instance
            new_user.save()

            # if the form is saved, redirect to the login template
            return redirect(reverse('users:login'))

    context = {
        "form": form
    }

    return render(request, 'signup.html' ,context)


def users_list(request):

    users = CustomUser.objects.all()

    context = {
        'users': users
    }
    
    return render(request, 'user-list.html', context) 

def profile(request):
    
    # blank image form
    image_form = ProfileImageUpdateForm()

    # when the form is submitted
    if request.method == 'POST':
        # instance of form with data and files from request
        image_form = ProfileImageUpdateForm(
            data=request.POST, 
            files=request.FILES,
        )
        # if the form contains a file
        if request.FILES:
            # validate the form
            if image_form.is_valid():
                
                current_user = CustomUser.objects.get(username=request.user.username)
                # get the current user object
                print("HAS PROFILE IMAGE: ", current_user.has_profile_image())

                # delete current profile, if it exists
                if current_user.has_profile_image():
                    old_image = ProfileImage.objects.get(
                        id=current_user.profile_image_id
                    )

                    old_image_name = PurePath(old_image.image.name).name
                    
                    if old_image_name != 'default_profile_image.jpg':
                        old_image_path = Path(
                            settings.MEDIA_ROOT / 
                            old_image.image.name
                        )

                        Path.unlink(old_image_path, missing_ok=True)

                        old_image.delete()
                else:
                    print(f'{current_user} does not have a profile image')
                # create a model object but don't save it yet
                new_profile_image = image_form.save(commit=False)
                
                # associate the new image with the current user
                current_user.profile_image = new_profile_image

                # img_file = request.FILES.get("profile_image")
                # img_name = img_file.name
                img = Image.open(new_profile_image.image)

                print("IMG: ",img)
                # img_extension = img_name.split(".")[-1].lower()

                # if img_extension == 'jpeg':
                #     img_extension = 'jpg'

                # if img.height > 500 or img.width > 500:
                #     output_size = (500, 500)
                #     img.thumbnail(output_size)

                # change the current user's profile image to the new profile image
                request.user.profile_image = new_profile_image
                new_profile_image.customuser = current_user
                
                image_form.save()
                request.user.save()


    context = {
        'img_form': image_form,
    }

    return(render(request, 'profile.html', context))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/login.html
{% extends 'base.html' %}

{% block content %}

    <h1>Login</h1>

    <!-- POST the form to the login view on login -->
    <form method="POST">
        {% csrf_token %}

        <!-- Render errors if any -->
        {{ form.non_field_errors }}

        <!-- render form fields manually -->
        <p>
            Username: <br>
            {{ form.username }}
            {{form.username.errors}}
        </p>

        <p>
            Password: <br>
            {{ form.password }}
            {{ form.password.errors }}

        </p>

        <input type="submit" value="Submit">
    </form>

    <p>
        Need an account?
        <a href="{% url 'users:signup'%}">Sign Up</a>
    </p>

{% endblock %}

templates/profile.html
{% extends 'base.html' %} 

{% block content %}

<h1>{{ user.username }}'s profile</h1>



<!-- enctype="multipart/form-data" is
    required to be able to upload the file -->
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}


  <!-- The field label will be styled and used
        as the button to bring up the file select menu.
        An input field with an id of 'id_image' will
        be generated by the Django form rendering -->
  <label for="id_image">
    <p>
      Select profile image
    </p>

    <!-- This is the original field and will
            be hidden because it looks gross and is
            difficult to customize -->
    <p id="profile-image-field">
        <!-- This will generate the input
                field with an id of 'id_image'-->
        {{ img_form.image }}
    </p>
  </label> 


  <!-- Button to submit the form -->
  <button type="submit">
    Update
  </button>
</form>


<img src="/media/{{ user.profile_image.image.name }}" alt="">
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}

    <h1>Sign Up</h1>

    <!-- POST the form to the signup view on Submit -->
    <form method="POST">
        {% csrf_token %}

        <!-- Render form errors if any -->
        {{ form.non_field_errors }}

        <!-- render form fields manually -->
        <p>
            Username: <br>
            {{ form.username }}
            {{ form.username.errors }}
        </p>

        <p>
            Password: <br>
            {{ form.password1 }}
            {{ form.password1.errors }}

        </p>
        <p>
            Verify Password: <br>
            {{ form.password2 }}
            {{ form.password2.errors }}
        </p>
        
        <input type="submit" value="Submit">
    </form>

    <p>
        Already have an account?
        <a href="{% url 'users:login' %}">Login</a>
    </p>

{% endblock %}

templates/user-list.html
{% extends 'base.html' %}

{% block content %}

<h1>Users</h1>
<ul>
    {% for usr in users %}
        <li>
            <a href="{% url 'users:profile'%}">
                {{ usr.username }}
            </a>
        </li>
    {% empty %}
        No users
    {% endfor%}
</ul>

{% endblock %}

templates/users.html
{% extends 'base.html' %}

{% block content %}
{% endblock %}